### ISSUE TITLE
AttributeError: 'ExecutionTime' object has no attribute 'should_be_rendered'

### ISSUE THREAD

**Issue by FlyingBird95** [RUGSoftEng/2018-PyDash.io#355]
INFO:werkzeug:127.0.0.1 - - [16/May/2018 15:15:32] "GET /api/dashboards/190c95f5-c697-4e51-82b9-68734914fc0f HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/patrickvogel/.local/share/virtualenvs/pydash-jkg4BLKf/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/patrickvogel/.local/share/virtualenvs/pydash-jkg4BLKf/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/patrickvogel/.local/share/virtualenvs/pydash-jkg4BLKf/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/patrickvogel/.local/share/virtualenvs/pydash-jkg4BLKf/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/patrickvogel/.local/share/virtualenvs/pydash-jkg4BLKf/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/patrickvogel/.local/share/virtualenvs/pydash-jkg4BLKf/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/patrickvogel/.local/share/virtualenvs/pydash-jkg4BLKf/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/patrickvogel/.local/share/virtualenvs/pydash-jkg4BLKf/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/patrickvogel/.local/share/virtualenvs/pydash-jkg4BLKf/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/patrickvogel/.local/share/virtualenvs/pydash-jkg4BLKf/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/patrickvogel/.local/share/virtualenvs/pydash-jkg4BLKf/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/patrickvogel/.local/share/virtualenvs/pydash-jkg4BLKf/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/patrickvogel/.local/share/virtualenvs/pydash-jkg4BLKf/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/patrickvogel/git/2018-PyDash.io/pydash/pydash_web/api_routes.py", line 64, in get_dashboard
    return controller.dashboard(dashboard_id)
  File "/Users/patrickvogel/git/2018-PyDash.io/pydash/pydash_web/controller/dashboards.py", line 44, in dashboard
    return jsonify(_dashboard_detail(db)), 200
  File "/Users/patrickvogel/git/2018-PyDash.io/pydash/pydash_web/controller/dashboards.py", line 102, in _dashboard_detail
    endpoints = [endpoint_dict(endpoint) for endpoint in dashboard.endpoints.values()]
  File "/Users/patrickvogel/git/2018-PyDash.io/pydash/pydash_web/controller/dashboards.py", line 102, in <listcomp>
    endpoints = [endpoint_dict(endpoint) for endpoint in dashboard.endpoints.values()]
  File "/Users/patrickvogel/git/2018-PyDash.io/pydash/pydash_web/controller/dashboards.py", line 98, in endpoint_dict
    'aggregates': endpoint.aggregated_data(),
  File "/Users/patrickvogel/git/2018-PyDash.io/pydash/pydash_app/dashboard/endpoint.py", line 59, in aggregated_data
    return self._aggregator.as_dict()
  File "/Users/patrickvogel/git/2018-PyDash.io/pydash/pydash_app/dashboard/aggregator/__init__.py", line 97, in as_dict
    for statistic in self.statistics.values() if statistic.should_be_rendered
  File "/Users/patrickvogel/git/2018-PyDash.io/pydash/pydash_app/dashboard/aggregator/__init__.py", line 97, in <dictcomp>
    for statistic in self.statistics.values() if statistic.should_be_rendered
AttributeError: 'ExecutionTime' object has no attribute 'should_be_rendered'

**Comment by Qqwy** [comment]
Did you re-seed after the last upgrade? I think it might be caused by that
